"""initial_tables

Revision ID: 7fb054f09b73
Revises: 
Create Date: 2026-02-06 16:47:12.240457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb054f09b73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iiko_department_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('territory', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_iiko_department_id'), 'branches', ['iiko_department_id'], unique=True)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('sync_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_table('daily_revenue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('order_type', sa.String(length=32), nullable=False),
    sa.Column('order_type_detail', sa.String(length=128), nullable=False),
    sa.Column('revenue_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('item_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('item_quantity_adjusted', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_revenue_branch_date', 'daily_revenue', ['branch_id', 'date'], unique=False)
    op.create_table('employee_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iiko_attendance_id', sa.String(length=64), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.String(length=64), nullable=True),
    sa.Column('role_name', sa.String(length=128), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=False),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), nullable=False),
    sa.Column('worked_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('iiko_payment_sum', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iiko_attendance_id')
    )
    op.create_index('ix_attendance_branch_date', 'employee_attendance', ['branch_id', 'date_from'], unique=False)
    op.create_table('staff_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staff_rates_employee_current', 'staff_rates', ['employee_id', 'is_current'], unique=False)
    op.create_table('writeoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('article_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sync_batch_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_writeoffs_branch_date', 'writeoffs', ['branch_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_writeoffs_branch_date', table_name='writeoffs')
    op.drop_table('writeoffs')
    op.drop_index('ix_staff_rates_employee_current', table_name='staff_rates')
    op.drop_table('staff_rates')
    op.drop_index('ix_attendance_branch_date', table_name='employee_attendance')
    op.drop_table('employee_attendance')
    op.drop_index('ix_daily_revenue_branch_date', table_name='daily_revenue')
    op.drop_table('daily_revenue')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_branches_iiko_department_id'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
