"""add writeoff detail columns

Revision ID: b7925989dcf6
Revises: 7fb054f09b73
Create Date: 2026-02-13 06:12:24.231134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7925989dcf6'
down_revision: Union[str, None] = '7fb054f09b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writeoffs', sa.Column('document_number', sa.String(length=64), nullable=True))
    op.add_column('writeoffs', sa.Column('account_name', sa.String(length=255), nullable=True))
    op.add_column('writeoffs', sa.Column('product_name', sa.String(length=255), nullable=True))
    op.add_column('writeoffs', sa.Column('item_quantity', sa.Numeric(precision=12, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writeoffs', 'item_quantity')
    op.drop_column('writeoffs', 'product_name')
    op.drop_column('writeoffs', 'account_name')
    op.drop_column('writeoffs', 'document_number')
    # ### end Alembic commands ###
