"""add waiter_checks table

Revision ID: f9e0c425fc3e
Revises: b7925989dcf6
Create Date: 2026-02-21 17:50:56.441815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e0c425fc3e'
down_revision: Union[str, None] = 'b7925989dcf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiter_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('waiter_name', sa.String(length=255), nullable=False),
    sa.Column('check_count', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('avg_check', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'date', 'waiter_name', name='uq_waiter_checks_branch_date_waiter')
    )
    op.create_index('ix_waiter_checks_branch_date', 'waiter_checks', ['branch_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waiter_checks_branch_date', table_name='waiter_checks')
    op.drop_table('waiter_checks')
    # ### end Alembic commands ###
